-- MySQL Script generated by MySQL Workbench
-- Sat Sep 24 23:40:21 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema learner_academy_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `learner_academy_db` DEFAULT CHARACTER SET utf8 ;
USE `learner_academy_db` ;

-- -----------------------------------------------------
-- Table `Classroom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Classroom` ;

CREATE TABLE IF NOT EXISTS `Classroom` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Student` ;

CREATE TABLE IF NOT EXISTS `Student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NULL,
  `lastName` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NULL,
  `Class_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Student_Class1_idx` (`Class_id` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Class1`
    FOREIGN KEY (`Class_id`)
    REFERENCES `Classroom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Subject`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Subject` ;

CREATE TABLE IF NOT EXISTS `Subject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Teacher` ;

CREATE TABLE IF NOT EXISTS `Teacher` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(255) NULL,
  `lastName` VARCHAR(255) NULL,
  `email` VARCHAR(255) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Subject_Class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Subject_Class` ;

CREATE TABLE IF NOT EXISTS `Subject_Class` (
  `subject_class_id` INT NOT NULL AUTO_INCREMENT,
  `subject_id` INT NOT NULL,
  `class_id` INT NOT NULL,
  `teacher_id` INT NULL,
  INDEX `fk_Subject_Class_Subject1_idx` (`subject_id` ASC) VISIBLE,
  INDEX `fk_Subject_Class_Teacher1_idx` (`teacher_id` ASC) VISIBLE,
  PRIMARY KEY (`subject_class_id`),
  CONSTRAINT `fk_Subject_Class_Class`
    FOREIGN KEY (`class_id`)
    REFERENCES `Classroom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subject_Class_Subject1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `Subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subject_Class_Teacher1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `Teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
